_target_: src.models.crnn_ctc_module.CRNN_CTC_Module
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}

optimizer:
  _target_: torch.optim.RMSprop
  _partial_: true
  lr: 0.0003

# scheduler: 
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.2
#   patience: 15
#   verbose: true

scheduler: null

net: 
  _target_: src.models.components.cnn_san_arce.CNN_SAN_Arce
  img_size: ${data.train.train_config.img_size}
  tokenizer: ${tokenizer}
  cnn_dropout: 0.2
  dropout: 0.1
  n_heads: 4
  n_layers: 4
  d_model: 192
  hidden_dim: 512

compile: false