_target_: src.models.hybrid_module.HybridModule
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}

log_val_metrics: false

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  # weight_decay: 0.001

scheduler: null 

net: 
  _target_: src.models.components.crnn_michael_att.CRNN_Michael
  input_size: 128 
  hidden_size: 256
  att_dim:  128
  tokenizer: ${tokenizer}
  char_embedding_size: 64
  dropout_encoder: 0.5
  layers_encoder: 3
  layers_decoder: 1

compile: false