_target_: src.models.crnn_ctc_module.CRNN_CTC_Module
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}


optimizer:
  _target_: torch.optim.RMSprop
  _partial_: true
  lr: 0.0003
  # weight_decay: 0.001

scheduler: null
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

net: 
  _target_: src.models.components.crnn_ctc_puig.CRNN_Puig 
  input_size: 1280 
  hidden_size: 256
  num_layers: 5
  vocab_size: 101

compile: false