_target_: src.models.crnn_ctc_module.CRNN_CTC_Module
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}

log_val_metrics: false

optimizer:
  _target_: torch.optim.RMSprop
  _partial_: true
  lr: 0.0003

scheduler: null

net: 
  _target_: src.models.components.crnn_ctc_puig.CRNN_Puig 
  input_size: 1280 
  hidden_size: 256
  num_layers: 5
  tokenizer: ${tokenizer}

compile: false