_target_: src.models.crnn_ctc_module.CRNN_CTC_Module
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.5 

# optimizer: 
#   _target_: src.optimizers.sam.SAM
#   _partial_: true
#   base_optimizer: 
#     _target_: torch.optim.AdamW
#     _partial_: true
#     lr: 1e-7
#     betas: [0.9, 0.999]
#     weight_decay: 0.5

# scheduler: 
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.8
#   patience: 20
#   verbose: true

# scheduler: null

scheduler: # CosineAnnealingWarmRestarts
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 1000
  T_mult: 2
  eta_min: 1e-3

net: 
  _target_: src.models.components.htr_vit.MaskedAutoencoderViT
  img_size: ${data.train.train_config.img_size}
  # patch_size: (4, 64)
  # patch_size: (64, 4)
  patch_size: [64, 4]
  embed_dim: 768
  depth: 4
  num_heads: 6
  mlp_ratio: 4
  tokenizer: ${tokenizer}
  
compile: false