_target_: src.models.crnn_ctc_module.CRNN_CTC_Module
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}

log_val_metrics: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.5 

scheduler: null

net: 
  _target_: src.models.components.htr_vit.MaskedAutoencoderViT
  img_size: ${data.train.train_config.img_size}
  patch_size: [64, 4]
  embed_dim: 768
  depth: 4
  num_heads: 6
  mlp_ratio: 4
  tokenizer: ${tokenizer}
  
compile: false