_target_: src.models.hybrid_module.HybridModule
# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}
tokenizer: ${tokenizer}

log_val_metrics: false

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  # weight_decay: 0.001

scheduler: null

net: 
  _target_: src.models.components.light_barrere.Light_Barrere
  image_size: ${data.train.train_config.img_size}
  hidden_dim: 256
  intermediate_ffn_dim: 1024
  dropout: 0.2
  n_heads: 4
  encoder_layers: 4
  decoder_layers: 4
  char_embedding_size: 256
  tokenizer: ${tokenizer}

compile: false