_target_: src.models.transformers_hf.HTRTransformerLitModule

# Accessing to data in configs/train_htr.yaml
datasets: ${data}
_logger: ${logger}


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  # weight_decay: 0.001

scheduler: null
  # _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  # _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

visualize_attention: False

net: 
  _target_: src.models.components.swin_transformer.SwinTransformer
  use_backbone: False
  patch_per_column: False
  image_size: ${data.train.train_config.img_size}
  num_channels: 3
  patch_size: 4
  encoder_layers: [2,2,6,2]
  encoder_attention_heads: [2,4,8,16]
  vocab_size: 101
  d_model: 64
  masking_noise: 0.0
  dropout: 0.1
  decoder_layers: 4
  decoder_attention_heads: 4
  decoder_ffn_dim: 256
  activation_function: 'gelu'
  window_size: 7
  mlp_ratio: 4.0
  qkv_bias: True
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  drop_path_rate: 0.0
  hidden_act: "gelu"
  encoder_stride: 32
  
compile: false
