# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: "."

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to real data
real_data: ${paths.data_dir}/htr_datasets/

# path to synthetic data
synth_data: ${paths.data_dir}/synth/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

checkpoints_dir: ${paths.root_dir}/checkpoints/

checkpoints_tokenizers: ${paths.root_dir}/checkpoints_tokenizers/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
