defaults:
  - _self_
  # - model_checkpoint
  - model_checkpoint_id
  - model_checkpoint_heldout
  - early_stopping
  - model_summary
  # - rich_progress_bar
  # - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/acc"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/acc"
  patience: 30
  mode: "min"

model_summary:
  max_depth: -1
